/* Generated By:JavaCC: Do not edit this line. PlanStringConverterConstants.java */
package sapa.planStringConverter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PlanStringConverterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLAN = 5;
  /** RegularExpression Id. */
  int COST = 6;
  /** RegularExpression Id. */
  int DASH = 7;
  /** RegularExpression Id. */
  int EXCLAMATION = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int OBRA = 10;
  /** RegularExpression Id. */
  int CBRA = 11;
  /** RegularExpression Id. */
  int OBBRA = 12;
  /** RegularExpression Id. */
  int CBBRA = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int NAME = 16;
  /** RegularExpression Id. */
  int CONSTANT = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Plan\"",
    "\"cost\"",
    "\"-\"",
    "\"!\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<FLOAT>",
    "<EXPONENT>",
    "<NAME>",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
