/* Generated By:JavaCC: Do not edit this line. PlaceGrammarConstants.java */
package epclaim.compiler.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PlaceGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OBRA = 8;
  /** RegularExpression Id. */
  int CBRA = 9;
  /** RegularExpression Id. */
  int OCBRA = 10;
  /** RegularExpression Id. */
  int CCBRA = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int QUESTION = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int DOT = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int CONSTANT = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int VARIABLE = 26;
  /** RegularExpression Id. */
  int DEFINE_AGENT = 27;
  /** RegularExpression Id. */
  int DEFINE_ENVIRONMENT = 28;
  /** RegularExpression Id. */
  int DEFINE_ARTIFACT = 29;
  /** RegularExpression Id. */
  int KNOWLEDGE = 30;
  /** RegularExpression Id. */
  int ADD_EFFECT = 31;
  /** RegularExpression Id. */
  int DELETE_EFFECT = 32;
  /** RegularExpression Id. */
  int GOALS = 33;
  /** RegularExpression Id. */
  int ARTIFACTS = 34;
  /** RegularExpression Id. */
  int CONNECTED_TO = 35;
  /** RegularExpression Id. */
  int PARENT = 36;
  /** RegularExpression Id. */
  int ACTIONS = 37;
  /** RegularExpression Id. */
  int MESSAGE = 38;
  /** RegularExpression Id. */
  int ACTIVITIES = 39;
  /** RegularExpression Id. */
  int CONDITION = 40;
  /** RegularExpression Id. */
  int HASKNOWLEDGE = 41;
  /** RegularExpression Id. */
  int DO = 42;
  /** RegularExpression Id. */
  int SEND = 43;
  /** RegularExpression Id. */
  int THIS = 44;
  /** RegularExpression Id. */
  int TELL = 45;
  /** RegularExpression Id. */
  int CALL = 46;
  /** RegularExpression Id. */
  int JAVA = 47;
  /** RegularExpression Id. */
  int NEWAGENT = 48;
  /** RegularExpression Id. */
  int KILL = 49;
  /** RegularExpression Id. */
  int IN = 50;
  /** RegularExpression Id. */
  int OUT = 51;
  /** RegularExpression Id. */
  int MOVE = 52;
  /** RegularExpression Id. */
  int DURATION = 53;
  /** RegularExpression Id. */
  int EFFECTS = 54;
  /** RegularExpression Id. */
  int REMOVEKNOWLEDGE = 55;
  /** RegularExpression Id. */
  int ORDERED = 56;
  /** RegularExpression Id. */
  int UNORDERED = 57;
  /** RegularExpression Id. */
  int AGENT_IN = 58;
  /** RegularExpression Id. */
  int NAME = 59;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"?\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"null\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"and\"",
    "\"or\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<VARIABLE>",
    "\"defineAgent\"",
    "\"defineEnvironment\"",
    "\"defineArtifact\"",
    "\"knowledge\"",
    "\"addEffects\"",
    "\"deleteEffects\"",
    "\"goals\"",
    "\"artifacts\"",
    "\"connectedTo\"",
    "\"parent\"",
    "\"actions\"",
    "\"message\"",
    "\"activities\"",
    "\"condition\"",
    "\"hasKnowledge\"",
    "\"do\"",
    "\"send\"",
    "\"this\"",
    "\"tell\"",
    "\"call\"",
    "\"java\"",
    "\"newAgent\"",
    "\"kill\"",
    "\"in\"",
    "\"out\"",
    "\"move\"",
    "\"duration\"",
    "\"effects\"",
    "\"removeKnowledge\"",
    "\"ordered\"",
    "\"unordered\"",
    "\"agent_in\"",
    "<NAME>",
  };

}
