/* Generated By:JavaCC: Do not edit this line. PlaceGrammarConstants.java */
package epclaim.compiler.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PlaceGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OBRA = 5;
  /** RegularExpression Id. */
  int CBRA = 6;
  /** RegularExpression Id. */
  int OCBRA = 7;
  /** RegularExpression Id. */
  int CCBRA = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int QUESTION = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int MULTIPLY = 12;
  /** RegularExpression Id. */
  int DIVIDE = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int NULL = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int DOT = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int DEFINE_AGENT = 22;
  /** RegularExpression Id. */
  int DEFINE_ENVIRONMENT = 23;
  /** RegularExpression Id. */
  int DEFINE_ARTIFACT = 24;
  /** RegularExpression Id. */
  int KNOWLEDGE = 25;
  /** RegularExpression Id. */
  int GOALS = 26;
  /** RegularExpression Id. */
  int ARTIFACTS = 27;
  /** RegularExpression Id. */
  int CONNECTED_TO = 28;
  /** RegularExpression Id. */
  int PARENT = 29;
  /** RegularExpression Id. */
  int ACTIONS = 30;
  /** RegularExpression Id. */
  int MESSAGE = 31;
  /** RegularExpression Id. */
  int ACTIVITIES = 32;
  /** RegularExpression Id. */
  int CONDITION = 33;
  /** RegularExpression Id. */
  int HASKNOWLEDGE = 34;
  /** RegularExpression Id. */
  int DO = 35;
  /** RegularExpression Id. */
  int SEND = 36;
  /** RegularExpression Id. */
  int THIS = 37;
  /** RegularExpression Id. */
  int TELL = 38;
  /** RegularExpression Id. */
  int CALL = 39;
  /** RegularExpression Id. */
  int JAVA = 40;
  /** RegularExpression Id. */
  int NEWAGENT = 41;
  /** RegularExpression Id. */
  int KILL = 42;
  /** RegularExpression Id. */
  int IN = 43;
  /** RegularExpression Id. */
  int OUT = 44;
  /** RegularExpression Id. */
  int MOVE = 45;
  /** RegularExpression Id. */
  int DURATION = 46;
  /** RegularExpression Id. */
  int EFFECTS = 47;
  /** RegularExpression Id. */
  int REMOVEKNOWLEDGE = 48;
  /** RegularExpression Id. */
  int ORDERED = 49;
  /** RegularExpression Id. */
  int UNORDERED = 50;
  /** RegularExpression Id. */
  int NAME = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"?\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"null\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"and\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"defineAgent\"",
    "\"defineEnvironment\"",
    "\"defineArtifact\"",
    "\"knowledge\"",
    "\"goals\"",
    "\"artifacts\"",
    "\"connectedTo\"",
    "\"parent\"",
    "\"actions\"",
    "\"message\"",
    "\"activities\"",
    "\"condition\"",
    "\"hasKnowledge\"",
    "\"do\"",
    "\"send\"",
    "\"this\"",
    "\"tell\"",
    "\"call\"",
    "\"java\"",
    "\"newAgent\"",
    "\"kill\"",
    "\"in\"",
    "\"out\"",
    "\"move\"",
    "\"duration\"",
    "\"effects\"",
    "\"removeKnowledge\"",
    "\"ordered\"",
    "\"unordered\"",
    "<NAME>",
  };

}
